version: "3"
services:
    zbxpromexporter:
        container_name: zbxpromexporter  
        build: .
        image: zensix/zbxpromexporter 
        volumes:
        - ${PWD}/config.json:/usr/src/app/config.json

        ports:
            - "3001:3000"
networks:
    default:
        external:
            name: traefik_default 
